socket:
  debugLogger: false
  printLogger: true
  client-work-size: 2 #netty client work 线程数量
  bossThreadSize: 2 #线程池的线程数量，共享
  workerThreadSize: 10 #线程池的线程数量，共享
  server:
    config:
      port: 18001
      idleTimeout: 30 # 单位秒
      scanMessages: ["wxdgaming.spring.game.server.proto"]
      scanHandlers: ["wxdgaming.spring.game.script"]
      enable-web-socket: true
      web-socket-prefix: "/wxd-gaming"
      sslProtocolType: TLSV12 # TLSV12  TLSV1 SSLV3 SSL
      jks_path: "jks/wxdtest-1.8.jks"
      jks_pwd_path: "jks/wxdtest-1.8.jks.pwd"

#  client:
#    config:
#      host: 127.0.0.1
#      port: 18001
#      scanMessages: ["wxdgaming.spring.game.server.proto"]
#      enable-reconnection: true
#      idleTimeout: 30 # 单位秒
#      connectTimeout: 500 # 单位毫秒
#      enable-ssl: false
#      sslProtocolType: TLSV12 # TLSV12  TLSV1 SSLV3 SSL
#      jks_path: "jks/wxdtest-1.8.jks"
#      jks_pwd_path: "jks/wxdtest-1.8.jks.pwd"
